name: Android Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install NDK
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;25.2.9519653"
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      # .so dosyalarını bul ve "collected_libs" klasörüne kopyala
      - name: Collect SO Files
        run: |
          mkdir -p collected_libs
          find . -name "*.so" -exec cp {} ./collected_libs/ \;
          echo "Bulunan dosyalar:"
          ls ./collected_libs/

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Full_Project_Output
          path: |
            **/*.apk
            collected_libs/
            
